{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ejml",
    "module": "ejml-fsparse",
    "version": "0.43.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ejml",
          "module": "ejml-core",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-fdense",
          "version": {
            "requires": "0.43.1"
          }
        }
      ],
      "files": [
        {
          "name": "ejml-fsparse-0.43.1.jar",
          "url": "ejml-fsparse-0.43.1.jar",
          "size": 95287,
          "sha512": "4f39d248d1e659089523fad3eacc4d973c830b767a7198dfef65492590e85619045b8fdc4791878deebc0aa5b6e1c560a55e7ff18a8e09c5a4ba290ba50ca5a1",
          "sha256": "23ef080a75893f7d1b0b2f16bd937ddbc4199a2999c246d905a55663a4d54a91",
          "sha1": "a059f579095b9841dbe32113b96450413b401db3",
          "md5": "ac6d3857036642db857b4d613d8347e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ejml",
          "module": "ejml-core",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-fdense",
          "version": {
            "requires": "0.43.1"
          }
        }
      ],
      "files": [
        {
          "name": "ejml-fsparse-0.43.1.jar",
          "url": "ejml-fsparse-0.43.1.jar",
          "size": 95287,
          "sha512": "4f39d248d1e659089523fad3eacc4d973c830b767a7198dfef65492590e85619045b8fdc4791878deebc0aa5b6e1c560a55e7ff18a8e09c5a4ba290ba50ca5a1",
          "sha256": "23ef080a75893f7d1b0b2f16bd937ddbc4199a2999c246d905a55663a4d54a91",
          "sha1": "a059f579095b9841dbe32113b96450413b401db3",
          "md5": "ac6d3857036642db857b4d613d8347e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-fsparse-0.43.1-javadoc.jar",
          "url": "ejml-fsparse-0.43.1-javadoc.jar",
          "size": 235678,
          "sha512": "661a55354e8c245c223bf1abebe51cb3b9f1c82fd06b899ab226c924e7c39cd96469735f63d19d3365c873f0ad440c8596f0ab6085f4dcf6b3f70ce61ed1d02d",
          "sha256": "29505aaf62a477e68108e71b2c0fb2678c45cbb22a55a00d8e709898449e63b0",
          "sha1": "478164952d3e5cb246eb515edb61cf02caeb61ee",
          "md5": "68b7afd24d22adc055f0f2a0c6e2fcf1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-fsparse-0.43.1-sources.jar",
          "url": "ejml-fsparse-0.43.1-sources.jar",
          "size": 81891,
          "sha512": "fe53bee04ffc634875717625463797eec531c6f1b68293b95c5e11d997dd844ada3b3f500749a69ca660134ece2d24f935f0319715b7304492f377d1fd037588",
          "sha256": "60140ed53bcceb8dfa0972049b7b74b2724efc618cfcd5cffe04d21df06d9136",
          "sha1": "1586c3f5bbca7198989e07bdc3efb153df4563ea",
          "md5": "03011f1ae6ab10d13aa889b1f99e06e0"
        }
      ]
    }
  ]
}
