{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ejml",
    "module": "ejml-zdense",
    "version": "0.43.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ejml",
          "module": "ejml-core",
          "version": {
            "requires": "0.43.1"
          }
        }
      ],
      "files": [
        {
          "name": "ejml-zdense-0.43.1.jar",
          "url": "ejml-zdense-0.43.1.jar",
          "size": 87006,
          "sha512": "6c8668d0b92b426cbfdddc387fa55d23efc1663a4b8370d1c9faec0ca39db1f57562a963764524ad8dddd8756d81b2f72c04708f5deb5f1187c7b2a7d7efeea0",
          "sha256": "dc47e7395fb7dd3652f0f2e82566f193824ba3762fc709487e03d76bba13e070",
          "sha1": "5b8b11fd46abafe095c37e7926896adccd58277e",
          "md5": "1b7736b4852070554f2561428015f280"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ejml",
          "module": "ejml-core",
          "version": {
            "requires": "0.43.1"
          }
        }
      ],
      "files": [
        {
          "name": "ejml-zdense-0.43.1.jar",
          "url": "ejml-zdense-0.43.1.jar",
          "size": 87006,
          "sha512": "6c8668d0b92b426cbfdddc387fa55d23efc1663a4b8370d1c9faec0ca39db1f57562a963764524ad8dddd8756d81b2f72c04708f5deb5f1187c7b2a7d7efeea0",
          "sha256": "dc47e7395fb7dd3652f0f2e82566f193824ba3762fc709487e03d76bba13e070",
          "sha1": "5b8b11fd46abafe095c37e7926896adccd58277e",
          "md5": "1b7736b4852070554f2561428015f280"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-zdense-0.43.1-javadoc.jar",
          "url": "ejml-zdense-0.43.1-javadoc.jar",
          "size": 255240,
          "sha512": "0cfa1228d97f938a8aa045933bc8644b28905f053f590fb1793a5ea7ed32cb96f01671bb129a843879aa940637debb102d1440c35a1b2322e23b428265b59591",
          "sha256": "cfdb5043bb7e1df5241b9d3523e88fa73398acc922eddfadce481bf0117321f8",
          "sha1": "9b03bae675d2d87f417a43b8e299222e5dbcfa68",
          "md5": "57629090697b082d117770a371356275"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-zdense-0.43.1-sources.jar",
          "url": "ejml-zdense-0.43.1-sources.jar",
          "size": 76496,
          "sha512": "ad4f9389f1d604ea8208079854dd0894787a2294db8f0a3b34e677bff3af57ca63b1404fda385fdd7fb942b75fad251babcf918127fdd4e870bb0359ae4b0924",
          "sha256": "acb70d65983b1d4fb9dfa26d85abf15e893c2d5901f4a6a7c47c9715643f9c52",
          "sha1": "adfe4f983eb136a571d83508691d120df485302e",
          "md5": "da412a63e3580c523d46026d8ae2d9f8"
        }
      ]
    }
  ]
}
