{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.wpi.first",
    "module": "native-utils",
    "version": "2025.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first",
          "module": "ToolchainPlugin",
          "version": {
            "requires": "2025.6.0"
          }
        },
        {
          "group": "edu.wpi.first",
          "module": "gradle-cpp-vscode",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "native-utils-2025.6.0.jar",
          "url": "native-utils-2025.6.0.jar",
          "size": 841804,
          "sha512": "de5bad482a8491647d8892915913cfbe0481a7c3421b944cf7222084c27f44b983e2694b810aaee8cc9cdcb00e6584d74e9a361124b8cd125297165c55529973",
          "sha256": "92283e5dffbab406efdd3e9ae4c985918b7422866de7572a0424959d547adccd",
          "sha1": "ca6362ea1a75473aef5ef2a5ebe1ff3cc7246014",
          "md5": "78d1c40fb4fdb13fb5e5d9556f8f158f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ajoberstar.grgit",
          "module": "grgit-core",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "edu.wpi.first",
          "module": "ToolchainPlugin",
          "version": {
            "requires": "2025.6.0"
          }
        },
        {
          "group": "edu.wpi.first",
          "module": "gradle-cpp-vscode",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "native-utils-2025.6.0.jar",
          "url": "native-utils-2025.6.0.jar",
          "size": 841804,
          "sha512": "de5bad482a8491647d8892915913cfbe0481a7c3421b944cf7222084c27f44b983e2694b810aaee8cc9cdcb00e6584d74e9a361124b8cd125297165c55529973",
          "sha256": "92283e5dffbab406efdd3e9ae4c985918b7422866de7572a0424959d547adccd",
          "sha1": "ca6362ea1a75473aef5ef2a5ebe1ff3cc7246014",
          "md5": "78d1c40fb4fdb13fb5e5d9556f8f158f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-utils-2025.6.0-javadoc.jar",
          "url": "native-utils-2025.6.0-javadoc.jar",
          "size": 322957,
          "sha512": "111a882f07f651f91694d5bc46c8ce9d77f378a96545803da9b6820f294b6e0f59f7fef41ca5b0d9a61438a9fec67f96bae9ce8b0b2348a8744f8976fcd73cf0",
          "sha256": "29bce8e1671ec93e22c05a31d002c87bb491634b6111efb069b3319b2aeaa8cc",
          "sha1": "8361860ab4e617ea24c5eab8bddf5cbe81e31f77",
          "md5": "460d59f3481482537ae3c296126f3d45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-utils-2025.6.0-sources.jar",
          "url": "native-utils-2025.6.0-sources.jar",
          "size": 760599,
          "sha512": "d707aab87c75b0b3b03536589e20647416751e502db599d89616d35b844de07ab78c5b13c853074b035f2e146b5ce05e0ce92a32f09eb37268d818a2deff79f3",
          "sha256": "15c348a7f75d2bcbc855f0fee663dfaf04fcdfa2aea1a5d6991bac3375a497e7",
          "sha1": "0e92f77b5b3ddeb4793310908162f6f4209571df",
          "md5": "d368e7bc6cb4f8c39ce9042e81c47106"
        }
      ]
    }
  ]
}
