{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ejml",
    "module": "ejml-fdense",
    "version": "0.43.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ejml",
          "module": "ejml-core",
          "version": {
            "requires": "0.43.1"
          }
        }
      ],
      "files": [
        {
          "name": "ejml-fdense-0.43.1.jar",
          "url": "ejml-fdense-0.43.1.jar",
          "size": 406935,
          "sha512": "ef7d4b515109c9dcac76497d8dc13951d5473bbf22ca7b15e26f16c49ee02a09e726db90708e3201039eafcfb67d2c63f0eb3cf71aa5d97a3ef23045c24d4716",
          "sha256": "67dc4bebaa52a9864c2028ad150444a22227792a712bbc13f5d0c1ebe836b029",
          "sha1": "97806ca2f8df28a92152edee1cac17577b103582",
          "md5": "d87dcbfffd1c51afc65793b4b7a67500"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ejml",
          "module": "ejml-core",
          "version": {
            "requires": "0.43.1"
          }
        }
      ],
      "files": [
        {
          "name": "ejml-fdense-0.43.1.jar",
          "url": "ejml-fdense-0.43.1.jar",
          "size": 406935,
          "sha512": "ef7d4b515109c9dcac76497d8dc13951d5473bbf22ca7b15e26f16c49ee02a09e726db90708e3201039eafcfb67d2c63f0eb3cf71aa5d97a3ef23045c24d4716",
          "sha256": "67dc4bebaa52a9864c2028ad150444a22227792a712bbc13f5d0c1ebe836b029",
          "sha1": "97806ca2f8df28a92152edee1cac17577b103582",
          "md5": "d87dcbfffd1c51afc65793b4b7a67500"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-fdense-0.43.1-javadoc.jar",
          "url": "ejml-fdense-0.43.1-javadoc.jar",
          "size": 806344,
          "sha512": "94d1101df1a8cd1adab59314ba9765ee4ffcdbd939be1c7eed332e6ea9cb9b29fb49d3456a09daccb8dec54bda81c49c1e5e97beac77cb8050d8221b3e05d2d8",
          "sha256": "618906f20c5f4ef71f93d31a061d972d09f74f6a95988a4fb2c89ba6bbfcffdc",
          "sha1": "7b62073696d52c7a67b53268fcb329de975b1846",
          "md5": "7779e34d38b83820cd661c5d26665797"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-fdense-0.43.1-sources.jar",
          "url": "ejml-fdense-0.43.1-sources.jar",
          "size": 375904,
          "sha512": "9a9ba571843d74a4be557801ba21036312c58a6c52a581d4a276f4d2086c72adf8a4e90fdc73d5c12db7108762ec2e43a34343f2918364dad5a164cad03eae66",
          "sha256": "2e80c50270011b7df28c55b2c8b632f37672e7c476c638745b7f0d3a0a33dd7e",
          "sha1": "6a212f233a86691236294baac3ee50e052caf23c",
          "md5": "6e909e250d7c651e22d1370cead2684a"
        }
      ]
    }
  ]
}
