{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ejml",
    "module": "ejml-core",
    "version": "0.43.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ejml-core-0.43.1.jar",
          "url": "ejml-core-0.43.1.jar",
          "size": 268866,
          "sha512": "d401ca0ee0e80d3499b3ae8b4cd3ed5a7e5a473c9bf43eeadc5e4a78f9c48e45d0d718c1f317c2b144d694f1e1434c474fde52db83baac9f7aab03442564d76b",
          "sha256": "04136b8fabedf92c218914da3a837e27ba0aefbf924444d2aac243f77dbf208d",
          "sha1": "378837ef010fedab1a8c25f19079503aaf054a81",
          "md5": "16dd6c5491d9355af81b769674a3a071"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-core-0.43.1.jar",
          "url": "ejml-core-0.43.1.jar",
          "size": 268866,
          "sha512": "d401ca0ee0e80d3499b3ae8b4cd3ed5a7e5a473c9bf43eeadc5e4a78f9c48e45d0d718c1f317c2b144d694f1e1434c474fde52db83baac9f7aab03442564d76b",
          "sha256": "04136b8fabedf92c218914da3a837e27ba0aefbf924444d2aac243f77dbf208d",
          "sha1": "378837ef010fedab1a8c25f19079503aaf054a81",
          "md5": "16dd6c5491d9355af81b769674a3a071"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-core-0.43.1-javadoc.jar",
          "url": "ejml-core-0.43.1-javadoc.jar",
          "size": 819227,
          "sha512": "6829be14257449c09fe6bfa7deecce0317a0c020a3de553271b307ba78cc29534f94b60b0b223b24484a62ca1204b3c2ef13bda3d8b49cde61c62f97ab9fa73b",
          "sha256": "3b08e413f96cd4d83fe266ec2cf21a8389c12e114a5c0e31170577e49a3ec914",
          "sha1": "b7a30ca7f6763188a1b42e144752e2b1f6d9754e",
          "md5": "a1eb5ca44837dd8a5674933a20e755eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ejml-core-0.43.1-sources.jar",
          "url": "ejml-core-0.43.1-sources.jar",
          "size": 246383,
          "sha512": "9ab3ba57e3989a1bf1be008b50fdbedf9e2e95942066161ee501f4db574c32d559ee23a964d8ecbf1c36c230b594f51883895ccb23965f244966898b1354604f",
          "sha256": "5cd2c361205b746660a4aaf6ff5da5ba1bc3938a65c820495d250412408bb87d",
          "sha1": "dc8cfb8504de7c117d944fb7dfdece414a2d680a",
          "md5": "d9e582e1fc82700757c50b84ad31ff1c"
        }
      ]
    }
  ]
}
