{
  "formatVersion": "1.1",
  "component": {
    "group": "edu.wpi.first",
    "module": "ToolchainPlugin",
    "version": "2025.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first",
          "module": "DeployUtils",
          "version": {
            "requires": "2025.2.0"
          }
        },
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ToolchainPlugin-2025.6.0.jar",
          "url": "ToolchainPlugin-2025.6.0.jar",
          "size": 58778,
          "sha512": "bf14a8a9db9e367bc2fa87cc3c25c2ab0337e240c2be7a489d895eb8904884eedbd83946f3fecbda983a0527c116b5ef396c34db78283de06bc759540332bfc9",
          "sha256": "d359a95055cfc80a10c0f15db827bd2148491ef5b7ba11e121f90040fe5dd699",
          "sha1": "3b6aca377d25cb7d178c58f7dc63f295219452ab",
          "md5": "fb36f3c74b4631f0b39f57520d65d908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first",
          "module": "DeployUtils",
          "version": {
            "requires": "2025.2.0"
          }
        },
        {
          "group": "de.undercouch",
          "module": "gradle-download-task",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ToolchainPlugin-2025.6.0.jar",
          "url": "ToolchainPlugin-2025.6.0.jar",
          "size": 58778,
          "sha512": "bf14a8a9db9e367bc2fa87cc3c25c2ab0337e240c2be7a489d895eb8904884eedbd83946f3fecbda983a0527c116b5ef396c34db78283de06bc759540332bfc9",
          "sha256": "d359a95055cfc80a10c0f15db827bd2148491ef5b7ba11e121f90040fe5dd699",
          "sha1": "3b6aca377d25cb7d178c58f7dc63f295219452ab",
          "md5": "fb36f3c74b4631f0b39f57520d65d908"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ToolchainPlugin-2025.6.0-javadoc.jar",
          "url": "ToolchainPlugin-2025.6.0-javadoc.jar",
          "size": 174182,
          "sha512": "3d83d2d2ea9bf110e5f44c3eb79ae59d8646098ea64e5338490c8ffd95d11de4308a3d6b4c455ec7bcd357e4178b996a6faf4e13190142c6d2b15c30b049eff9",
          "sha256": "df388be60afa8bc4b2ca3c78e2c16ae9bb0980485cff0fbd40ea70a0bb7d55b9",
          "sha1": "925b28f1390cb9744d5cc1c90dfebda4c304cd54",
          "md5": "1d24c11f3688224a483e51a47d085d08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ToolchainPlugin-2025.6.0-sources.jar",
          "url": "ToolchainPlugin-2025.6.0-sources.jar",
          "size": 25199,
          "sha512": "9de0a6d386c0b1b9866a32f650db794be0b0fa29550c682088c14fabb188f20194d98e81cdb5fb0f7c1231cb712c2fd749e253f5bf96fe9c68e18ceb96f146b8",
          "sha256": "cc1b9335fb78760e1b33d0b04d129614ad3d3a7fcc0d9283b7fa5a65c7181783",
          "sha1": "bad47635d97109c77239c0e6864b2147eefe842a",
          "md5": "10c5f8f13ab9acef8279c99c795bd4cb"
        }
      ]
    }
  ]
}
