name: Build & Simulate

on: [push, pull_request]  # Trigger the workflow on push events

jobs:
  Simulate:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2025-24.04
    steps:

      - uses: actions/checkout@v4
      - name: Grant execute permission # just in case
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-gradle-caches-
            ${{ runner.os }}-gradle-wrapper-

      - name: Build Robot Code
        run: ./gradlew build

      - name: Test Robot Code
        run: ./gradlew test
    
      - name: Simulate Robot Code
        run: |
          timeout 20s ./gradlew simulateJava || exit_code=$?
          if [ $exit_code -eq 124 ]; then
            echo "Command exited with code 124, ignoring"
            exit 0
          else
            exit $exit_code
          fi
